local mc

local load_multicursor = LoadOnce(function()
    vim.pack.add({ "https://github.com/jake-stewart/multicursor.nvim" })
    mc = require("multicursor-nvim")
    mc.setup()

    mc.addKeymapLayer(function(layerSet)
        layerSet("n" , "<M-S-k>", function() mc.lineSkipCursor(-1) end, { desc = "Multicursor: skip line" })
        layerSet("n" , "<M-S-j>", function() mc.lineSkipCursor(1) end, { desc = "Multicursor: skip line" })
        layerSet("v", "<M-S-j>", function() mc.matchSkipCursor(1) end, { desc = "Multicursor: skip match" })
        layerSet("v", "<M-S-k>", function() mc.matchSkipCursor(-1) end, { desc = "Multicursor: skip match" })
        layerSet({ "n", "x" }, "<M-h>", mc.prevCursor, { desc = "Multicursor: prev cursor" })
        layerSet({ "n", "x" }, "<M-l>", mc.nextCursor, { desc = "Multicursor: next cursor" })
        layerSet({ "n", "x" }, "<M-x>", mc.deleteCursor, { desc = "Multicursor: delete cursor" })
        layerSet({ "n", "x" }, "<M-d>", mc.deleteCursor, { desc = "Multicursor: delete cursor" })
        layerSet("n", { "<C-[>" }, function()
            if not mc.cursorsEnabled() then
                mc.enableCursors()
            else
                mc.clearCursors()
            end
        end, { desc = "Multicursor: enable/clear cursors" })
    end)
end)

vim.keymap.set({ "n", "x" }, "<M-a>", function()
    load_multicursor()
    mc.matchAllAddCursors()
end, { desc = "Multicursor: add all matches" })
vim.keymap.set({ "n", "x" }, "<M-q>", function()
    load_multicursor()
    mc.toggleCursor()
end, { desc = "Multicursor: toggle cursor" })
vim.keymap.set({ "n" }, "<M-k>", function()
    load_multicursor()
    mc.lineAddCursor(-1)
end, { desc = "Multicursor: add cursor above" })
vim.keymap.set({ "n" }, "<M-j>", function()
    load_multicursor()
    mc.lineAddCursor(1)
end, { desc = "Multicursor: add cursor below" })
vim.keymap.set({ "v" }, "<M-j>", function()
    load_multicursor()
    mc.matchAddCursor(1)
end, { desc = "Multicursor: next match" })
vim.keymap.set({ "v" }, "<M-k>", function()
    load_multicursor()
    mc.matchAddCursor(-1)
end, { desc = "Multicursor: previous match" })

vim.keymap.set("x", "I", function()
    load_multicursor()
    mc.insertVisual()
end, { desc = "Multicursor: insert at starts" })
vim.keymap.set("x", "A", function()
    load_multicursor()
    mc.appendVisual()
end, { desc = "Multicursor: append at ends" })
